// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1SijngZd1l3zyUWRTtCIaZFfHcqFUNJ4',
    appId: '1:526448735012:web:49e40b7d513f0c56c339b1',
    messagingSenderId: '526448735012',
    projectId: 'loginregister-77344',
    authDomain: 'loginregister-77344.firebaseapp.com',
    storageBucket: 'loginregister-77344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4l9UcVIT-vUoz3JQW0jr_VMQI_-fVurA',
    appId: '1:526448735012:android:99b9382ddbc7f9b5c339b1',
    messagingSenderId: '526448735012',
    projectId: 'loginregister-77344',
    storageBucket: 'loginregister-77344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwwO_wrNHZSR3W0IQibR9_2AV-Vs4_5x4',
    appId: '1:526448735012:ios:c557e5dd0047c311c339b1',
    messagingSenderId: '526448735012',
    projectId: 'loginregister-77344',
    storageBucket: 'loginregister-77344.appspot.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwwO_wrNHZSR3W0IQibR9_2AV-Vs4_5x4',
    appId: '1:526448735012:ios:c557e5dd0047c311c339b1',
    messagingSenderId: '526448735012',
    projectId: 'loginregister-77344',
    storageBucket: 'loginregister-77344.appspot.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1SijngZd1l3zyUWRTtCIaZFfHcqFUNJ4',
    appId: '1:526448735012:web:3828d41d4a17cf13c339b1',
    messagingSenderId: '526448735012',
    projectId: 'loginregister-77344',
    authDomain: 'loginregister-77344.firebaseapp.com',
    storageBucket: 'loginregister-77344.appspot.com',
  );
}
